ItalianDeli/ViewModels/ShoppingCartViewModel.cs
using ItalianDeli.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ItalianDeli.ViewModel
{
    public class ShoppingCartViewModel
    {
        [Key]
        public List<Cart> CartItems { get; set; }
        public decimal CartTotal { get; set; }
    }
}

ItalianDeli/Controllers/CheckoutController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using ItalianDeli.Configuration;
using ItalianDeli.Models;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;

namespace ItalianDeli.Controllers
{
    [Authorize]
    public class CheckoutController : Controller
    {
        ApplicationDbContext storeDB = new ApplicationDbContext();
        AppConfigurations appConfig = new AppConfigurations();

        public List<String> CreditCardTypes { get { return appConfig.CreditCardType;} }

        //
        // GET: /Checkout/AddressAndPayment
        public ActionResult AddressAndPayment()
        {
            ViewBag.CreditCardTypes = CreditCardTypes;
            var userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            var user = userManager.FindById(User.Identity.GetUserId());
            var previousOrder = storeDB.Orders.FirstOrDefault(x => x.Username == User.Identity.Name);
            CheckoutViewModel checkoutViewModel = new CheckoutViewModel { User = user, Order = previousOrder };

            if (previousOrder != null || user != null)
                return View(checkoutViewModel);
            else
                return View();
        }

        //
        // POST: /Checkout/AddressAndPayment
        [HttpPost]
        public async Task<ActionResult> AddressAndPayment(FormCollection values)
        {
            ViewBag.CreditCardTypes = CreditCardTypes;
            string result =  values[9];
            string deliveryType = values[10];

            var checkoutViewModel = new CheckoutViewModel();
            TryUpdateModel(checkoutViewModel);
            checkoutViewModel.Order.CreditCard = result;

            checkoutViewModel.Order.DeliveryOption = Convert.ToInt32(deliveryType) == 0 ? Common.DeliveryOption.Pickup : Common.DeliveryOption.Delivery;

            try
            {
                checkoutViewModel.Order.Username = User.Identity.Name;
                checkoutViewModel.Order.Email = User.Identity.Name;
                checkoutViewModel.Order.OrderDate = DateTime.Now;

                /*
                     * Alot of repition but just added this to make saving to db work coz without it its throwing exception
                     * errors for required fields
                     */
                checkoutViewModel.Order.Address = checkoutViewModel.Order.Address;
                checkoutViewModel.Order.City = checkoutViewModel.Order.City;
                checkoutViewModel.Order.Country = checkoutViewModel.Order.Country;
                checkoutViewModel.Order.State = checkoutViewModel.Order.State;
                checkoutViewModel.Order.Phone = checkoutViewModel.Order.Phone;
                checkoutViewModel.Order.PostalCode = checkoutViewModel.Order.PostalCode;
                checkoutViewModel.Order.FirstName = checkoutViewModel.Order.FirstName;
                checkoutViewModel.Order.LastName = checkoutViewModel.Order.LastName;
                checkoutViewModel.Order.Total = (decimal) HttpContext.Session["CartTotal"];

                //var currentUserId = User.Identity.GetUserId();
                //if (checkoutViewModel.Order.SaveInfo && !checkoutViewModel.Order.Username.Equals("guest@guest.com"))
                //{

                //    var manager =
                //        new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
                //    var store = new UserStore<ApplicationUser>(new ApplicationDbContext());
                //    var ctx = store.Context;
                //    var currentUser = manager.FindById(User.Identity.GetUserId());

                //    currentUser.Address = checkoutViewModel.Order.Address;
                //    currentUser.City = checkoutViewModel.Order.City;
                //    currentUser.Country = checkoutViewModel.Order.Country;
                //    currentUser.State = checkoutViewModel.Order.State;
                //    currentUser.Phone = checkoutViewModel.Order.Phone;
                //    currentUser.PostalCode = checkoutViewModel.Order.PostalCode;
                //    currentUser.FirstName = checkoutViewModel.Order.FirstName;
                //    currentUser.LastName = checkoutViewModel.Order.LastName;

                //    //Save this back
                //    //http://stackoverflow.com/questions/20444022/updating-user-data-asp-net-identity
                //    //var result = await UserManager.UpdateAsync(currentUser);
                //    await ctx.SaveChangesAsync();

                //    await storeDB.SaveChangesAsync();
                //}


                //Save Order
                storeDB.Orders.Add(checkoutViewModel.Order);
                await storeDB.SaveChangesAsync();
                //Process the order
                var cart = ShoppingCart.GetCart(this.HttpContext);
                checkoutViewModel.Order = cart.CreateOrder(checkoutViewModel.Order);



                CheckoutController.SendOrderMessage(checkoutViewModel.Order.FirstName,
                    "New Order: " + checkoutViewModel.Order.OrderId,
                    checkoutViewModel.Order.ToString(checkoutViewModel.Order), appConfig.OrderEmail);

                return RedirectToAction("Complete",
                    new {id = checkoutViewModel.Order.OrderId});

            }
            catch (Exception ex)
            {
                if (ex is System.Data.Entity.Validation.DbEntityValidationException)
                {
                    // Retrieve the error messages as a list of strings.
                    var errorMessages = (ex as System.Data.Entity.Validation.DbEntityValidationException)
                        .EntityValidationErrors
                        .SelectMany(x => x.ValidationErrors)
                        .Select(x => x.ErrorMessage);

                    // Join the list to a single string.
                    var fullErrorMessage = string.Join("; ", errorMessages);

                    // Combine the original exception message with the new one.
                    var exceptionMessage = string.Concat(ex.Message, " The validation errors are: ", fullErrorMessage);
                }
                //Invalid - redisplay with errors
                return View(checkoutViewModel);
            }
        }

        //
        // GET: /Checkout/Complete
        public ActionResult Complete(int id)
        {
            // Validate customer owns this order
            bool isValid = storeDB.Orders.Any(
                o => o.OrderId == id &&
                o.Username == User.Identity.Name);

            if (isValid)
            {
                return View(id);
            }
            else
            {
                return View("Error");
            }
        }

        private static RestResponse SendOrderMessage(String toName, String subject, String body, String destination)
        {
            RestClient client = new RestClient();
            //fix this we have this up top too
            AppConfigurations appConfig = new AppConfigurations();
            client.BaseUrl = "https://api.mailgun.net/v2";
            client.Authenticator =
                   new HttpBasicAuthenticator("api",
                                              appConfig.EmailApiKey);
            RestRequest request = new RestRequest();
            request.AddParameter("domain",
                                appConfig.DomainForApiKey, ParameterType.UrlSegment);
            request.Resource = "{domain}/messages";
            request.AddParameter("from", appConfig.FromName + " <" + appConfig.FromEmail + ">");
            request.AddParameter("to", toName + " <" + destination + ">");
            request.AddParameter("subject", subject);
            request.AddParameter("html", body);
            request.Method = Method.POST;
            IRestResponse executor = client.Execute(request);
            return executor as RestResponse;
        }
    }
}

ItalianDeli/Controllers/ShoppingCartController.cs
using ItalianDeli.Models;
using ItalianDeli.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ItalianDeli.Controllers
{
    public class ShoppingCartController : Controller
    {

        ApplicationDbContext storeDB = new ApplicationDbContext();
        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            HttpContext.Session["CartTotal"] = cart.GetTotal();
            // Return the view
            return View(viewModel);
        }
        //
        // GET: /Store/AddToCart/5
        [HttpPost]
        public ActionResult AddToCart(int id)
        {
            // Retrieve the item from the database
            var addedItem = storeDB.Items
                .Single(item => item.ID == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            int count = cart.AddToCart(addedItem);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(addedItem.Name) +
                    " has been added to your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = count,
                DeleteId = id
            };
            HttpContext.Session["CartTotal"] = cart.GetTotal();
            return Json(results);

            // Go back to the main store page for more shopping
           // return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult UpdateCart(int id, int quantity)
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            if (quantity == 0)
            {
                return RemoveFromCart(id);
            }
            else if (quantity > 0)
            {
                string itemName = storeDB.Items
                    .Single(item => item.ID == id).Name;

                int itemCount = cart.UpdateCart(id, quantity);

                // Set up our ViewModel
                var results = new ShoppingCartUpdateViewModel
                {
                    Message = Server.HtmlEncode(itemName) +
                              " has updated in your shopping cart.",
                    CartTotal = cart.GetTotal(),
                    CartCount = cart.GetCount(),
                    ItemCount = itemCount,
                    DeleteId = id
                };
                HttpContext.Session["CartTotal"] = cart.GetTotal();
                return Json(results);
            }
            else
            {
                var results = new ShoppingCartUpdateViewModel
                {
                    Message = Server.HtmlEncode("Please enter a quantity greater than or equal to 0"),
                    CartTotal = cart.GetTotal(),
                    CartCount = cart.GetCount(),
                    ItemCount = cart.GetItemCount(id),
                    DeleteId = id
                };
                HttpContext.Session["CartTotal"] = cart.GetTotal();
                return Json(results);
            }
        }


        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the item to display confirmation

            // Get the name of the album to display confirmation
            string itemName = storeDB.Items
                .Single(item => item.ID == id).Name;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = "One (1) "+ Server.HtmlEncode(itemName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            HttpContext.Session["CartTotal"] = cart.GetTotal();
            return Json(results);
        }
        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }
}

ItalianDeli/Controllers/StoreController.cs
using ItalianDeli.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ItalianDeli.Controllers
{
    public class StoreController : Controller
    {
        ApplicationDbContext storeDB = new ApplicationDbContext();

        //
        // GET: /Store/

        public ActionResult Index()
        {
            var catagories = storeDB.Catagories.ToList();

            return View(catagories);
        }

        //
        // GET: /Store/Browse?genre=Disco

        public ActionResult Browse(string catagorie)
        {
            // Retrieve Genre and its Associated Items from database
            var catagorieModel = storeDB.Catagories.Include("Items")
                .Single(g => g.Name == catagorie);

            return View(catagorieModel);
        }

        //
        // GET: /Store/Details/5
        public ActionResult Details(int id)
        {
            var item = storeDB.Items.Find(id);

            return View(item);
        }

        //
        // GET: /Store/GenreMenu
        [ChildActionOnly]
        public ActionResult CatagorieMenu()
        {
            var catagories = storeDB.Catagories.ToList();

            return PartialView(catagories);
        }
    }
}

ItalianDeli/Views/ShoppingCart/CartSummary.cshtml
<a href='@Url.Action("Index", "ShoppingCart")'><strong>Cart</strong>  @*<span id="cart-status" class="badge">@ViewData["CartCount"]</span>*@
    @if(ViewData["CartCount"] != null && (int)ViewData["CartCount"] > 0)
    {
        <span id="cart-status" class="badge">@ViewData["CartCount"]</span>
    }
    else
    {
        <span id="cart-status" class="badge"></span>
    }
</a>

ItalianDeli/Views/ShoppingCart/Index.cshtml
@model ItalianDeli.ViewModel.ShoppingCartViewModel
@{
    ViewBag.Title = "Shopping Cart";
}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script type="text/javascript">
    $(function () {
        // Document.ready -> link up remove event handler
        $(".RemoveLink").click(function () {
            // Get the id from the link
            var recordToDelete = $(this).attr("data-id");
            if (recordToDelete != '') {
                // Perform the ajax post
                $.post("/ShoppingCart/RemoveFromCart", { "id": recordToDelete },
                    function (data) {
                        // Successful requests get here
                        // Update the page elements
                        if (data.ItemCount == 0) {
                            $('#row-' + data.DeleteId).fadeOut('slow');
                        } else {
                            $('#item-count-' + data.DeleteId).text(data.ItemCount);
                        }
                        $('#cart-total').html("<span>$</span>" + data.CartTotal);
                        $('#update-message').text(data.Message);
                        if(data.CartCount > 0)
                        {
                            $('#cart-status').text(data.CartCount);
                        }
                        else
                        {
                            $('#cart-status').text('');
                        }
                    });
            }
        });

        $(".UpdateLink").click(function () {
            var recordToUpdate = $(this).attr("data-id");
            var quantity = $("#CartQuantity" + recordToUpdate).val();
            //if (quantity >= 0) {
                $.post("/ShoppingCart/UpdateCart", { "id": recordToUpdate, "quantity": quantity },
                    function(data) {
                        if (data.ItemCount == 0) {
                            $('#row-' + data.DeleteId).fadeOut('slow');
                        }
                        $('#cart-total').html("<span>$</span>" + data.CartTotal);
                        $('#update-message').text(data.Message);
                        $("#QuantityError" + recordToUpdate).css('visibility', 'hidden');
                        if (data.CartCount > 0) {
                            $('#cart-status').text(data.CartCount);
                        } else {
                            $('#cart-status').text('');
                        }
                    });
            //} else {
            //    $("#QuantityError" + recordToUpdate).css('visibility', 'visible');
            //}
        });
    });
</script>
<h3>
    <em>Review</em> your cart:
</h3>

@{

    if (Model.CartItems.Count > 0) 
    {
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Order Summary</h3>
            </div>
            <div class="panel-body">

                <div id="update-message">
                </div>
                <table class="table table-striped table-hover ">
                    <thead>
                        <tr>
                            <th>
                                Item Name
                            </th>
                            <th>
                                Price (each)
                            </th>
                            <th>
                                Quantity
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    @foreach (var item in Model.CartItems)
                    {
                        <tr id="row-@item.ItemId" >
                            <td>
                                @Html.ActionLink(item.Item.Name, "Details", "Store", new { id = item.ID }, null)
                            </td>
                            <td>
                                <span>$</span>@item.Item.Price
                            </td>
                            @*<td id="item-count-@item.ItemId">
                                @item.Count
                            </td>*@
                            <td id="item-count-@item.ItemId">
                                @Html.TextBox("CartQuantity" + @item.ItemId, @item.Count)
                            </td>
                            <td>
                                <a href="#" class="UpdateLink"
                                   data-id="@item.ItemId">
                                    Update Quantity
                                </a>
                            </td>
                            @*<td id="QuantityError@item.ItemId" style="visibility: hidden">
                                Please enter a quantity greater than or equal to 0
                            </td>*@
                            <td>
                                <a href="#" class="RemoveLink"
                                   data-id="@item.ItemId">
                                    Remove
                                    from cart
                                </a>
                            </td>
                        </tr>
                    }
                    <tr class="info">
                        <td>
                            Total
                        </td>
                        <td></td>
                        <td></td>
                        <td id="cart-total">
                            <span>$</span>@Model.CartTotal
                        </td>
                    </tr>
                </table>
                <button type="button" class="btn btn-success btn-sm" onclick="location.href='@Url.Action("AddressAndPayment", "Checkout")'">
                    Check Out &raquo;
                </button>
            </div>
        </div>
    }
    else
    {
        <div>
            <p>
                There are no items in your cart currently. Please shop for something and add items..
            </p>
        </div>
    }
}